tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "boost"
brew "brew-cask-completion"
brew "sqlite"
brew "cmake"
brew "curl"
brew "dash"
brew "dos2unix"
brew "doxygen"
brew "gcc"
brew "git"
brew "git-lfs"
brew "graphviz"
brew "jsoncpp"
brew "make"
brew "mas"
brew "mysql"
brew "pyenv"
brew "pyenv-virtualenv"
brew "vim"
brew "wget"
brew "zsh-completions"
cask "adobe-creative-cloud"
cask "android-ndk"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "beyond-compare"
cask "brackets"
cask "clion"
cask "dash"
cask "google-chrome"
cask "iterm2"
cask "lastpass"
cask "mactex"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "raspberry-pi-imager"
cask "rectangle"
cask "slack"
cask "sublime-text"
cask "visual-studio-code"
cask "vnc-viewer"
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "MainStage", id: 634159523
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
